---
title: "air quality"
output: html_document
date: "2023-06-21"
---

```{r setup, include=FALSE}
library(tidyverse)
library(scales)
library(modelr)
library(lubridate)

theme_set(theme_bw())
knitr::opts_chunk$set(echo = TRUE)
```


```{r load-data}
city <- read_csv(gzfile('data/city_day_agg_cleaned.csv.gz'))
country <- read_csv(gzfile('data/country_day_agg_cleaned.csv.gz'))
lockdown_USA <- read_csv('data/lockdown_dates.csv') %>% filter(countryCode == 'USA')
lockdown_CHE <- read_csv('data/lockdown_dates.csv') %>% filter(countryCode == 'CHE')
longlat <- read_csv('data/openaq_cities.csv')

```



```{r NO2}
city_no2 <- city %>% 
  filter(parameter == 'no2') %>%
  mutate(year = ifelse(date > '2019-12-31', "2020", "before 2020")) %>% 
  group_by(city_id, year) %>%
  summarize(avg = mean(mean, na.rm = TRUE)) %>% 
  group_by(year) %>% 
  mutate(avg_by_year = median(avg))
  
freq_no2 <- table(city_no2$city_id)
city_no2 <- city_no2[city_no2$city_id %in% names(freq_no2)[freq_no2 == 2], ]


city_no2 %>%
  ggplot(aes(x = avg, color = year, fill = year)) +
  geom_density(color = 'black', alpha = 0.5, position = "identity")+
  geom_vline(aes(xintercept = avg_by_year, color = year)) +
  # scale_x_log10()+
  labs(title = "City - NO2",
       x = "NO2",
       y = "Density")

## MAP

no2_map_2020 <- city %>%
  filter(parameter == 'no2') %>% 
  filter((('2020-01-01' <= date) & (date <= '2020-05-31'))) %>% 
  group_by(city_id) %>%
  summarize(avg_2020 = mean(mean, na.rm = TRUE))

no2_map_before_2020 <- city %>% 
  filter(parameter == 'no2') %>%
  filter((('2017-01-01' <= date) & (date <= '2017-05-31')) | (('2018-01-01' <= date) & (date <= '2018-05-31')) | (('2019-01-01' <= date) & (date <= '2019-05-31'))) %>% 
  group_by(city_id) %>%
  summarize(avg_before_2020 = mean(mean, na.rm = TRUE))

no2_map <- inner_join(no2_map_2020, no2_map_before_2020, by = "city_id")
no2_map <- left_join(no2_map, longlat, by = "city_id")
no2_map <- no2_map %>% 
  mutate(pcent = ((avg_before_2020 - avg_2020)/avg_before_2020)*100)

world_map <- map_data("world")
ggplot() +
  geom_polygon(data = world_map,
               aes(x = long, y = lat, group = group),
               fill = "lightgray", color = "white") +
  geom_point(data = no2_map, 
             aes(x = Lon, y = Lat, color = pcent),
             size = 0.1, alpha = 0.5) +
  scale_color_gradient(low = "purple", high = "orange") +
  labs(title = "Map - NO2",
       x = "Longitude",
       y = "Latitude")








```


```{r O3}
city_o3 <- city %>% 
  filter(parameter == 'o3') %>%
  mutate(year = ifelse(date > '2019-12-31', "2020", "before 2020")) %>% 
  group_by(city_id, year) %>%
  summarize(avg = mean(mean, na.rm = TRUE)) %>% 
  group_by(year) %>% 
  mutate(avg_by_year = median(avg))
  
freq_o3 <- table(city_o3$city_id)
city_o3 <- city_o3[city_o3$city_id %in% names(freq_o3)[freq_o3 == 2], ]


city_o3 %>%
  ggplot(aes(x = avg, color = year, fill = year)) +
  geom_density(color = 'black', alpha = 0.5, position = "identity")+
  geom_vline(aes(xintercept = avg_by_year, color = year)) +
  # scale_x_log10()+
  labs(title = "City - O3",
       x = "O3",
       y = "Density")

## MAP

o3_map_2020 <- city %>%
  filter(parameter == 'o3') %>% 
  filter((('2020-01-01' <= date) & (date <= '2020-05-31'))) %>% 
  group_by(city_id) %>%
  summarize(avg_2020 = mean(mean, na.rm = TRUE))

o3_map_before_2020 <- city %>% 
  filter(parameter == 'o3') %>%
  filter((('2017-01-01' <= date) & (date <= '2017-05-31')) | (('2018-01-01' <= date) & (date <= '2018-05-31')) | (('2019-01-01' <= date) & (date <= '2019-05-31'))) %>% 
  group_by(city_id) %>%
  summarize(avg_before_2020 = mean(mean, na.rm = TRUE))

o3_map <- inner_join(o3_map_2020, o3_map_before_2020, by = "city_id")
o3_map <- left_join(o3_map, longlat, by = "city_id")
o3_map <- o3_map %>% 
  mutate(pcent = ((avg_before_2020 - avg_2020)/avg_before_2020)*100)

world_map <- map_data("world")
ggplot() +
  geom_polygon(data = world_map,
               aes(x = long, y = lat, group = group),
               fill = "lightgray", color = "white") +
  geom_point(data = o3_map, 
             aes(x = Lon, y = Lat, color = pcent),
             size = 0.1, alpha = 0.5) +
  scale_color_gradient(low = "purple", high = "orange") +
  labs(title = "Map - O3",
       x = "Longitude",
       y = "Latitude")
```


```{r PM25}
city_pm <- city %>% 
  filter(parameter == 'pm25') %>%
  mutate(year = ifelse(date > '2019-12-31', "2020", "before 2020")) %>% 
  group_by(city_id, year) %>%
  summarize(avg = mean(mean, na.rm = TRUE)) %>% 
  group_by(year) %>% 
  mutate(avg_by_year = median(avg))
  
freq_pm <- table(city_pm$city_id)
city_pm <- city_pm[city_pm$city_id %in% names(freq_pm)[freq_pm == 2], ]
  

city_pm %>%
  ggplot(aes(x = avg, color = year, fill = year)) +
  geom_density(color = 'black', alpha = 0.5, position = "identity")+
  geom_vline(aes(xintercept = avg_by_year, color = year)) +
  # scale_x_log10()+
  labs(title = "City - PM2.5",
       x = "PM2.5",
       y = "Density")

## MAP

pm_map_2020 <- city %>%
  filter(parameter == 'pm25') %>% 
  filter((('2020-01-01' <= date) & (date <= '2020-05-31'))) %>% 
  group_by(city_id) %>%
  summarize(avg_2020 = mean(mean, na.rm = TRUE))

pm_map_before_2020 <- city %>% 
  filter(parameter == 'pm25') %>%
  filter((('2017-01-01' <= date) & (date <= '2017-05-31')) | (('2018-01-01' <= date) & (date <= '2018-05-31')) | (('2019-01-01' <= date) & (date <= '2019-05-31'))) %>% 
  group_by(city_id) %>%
  summarize(avg_before_2020 = mean(mean, na.rm = TRUE))

pm_map <- inner_join(pm_map_2020, pm_map_before_2020, by = "city_id")
pm_map <- left_join(pm_map, longlat, by = "city_id")
pm_map <- pm_map %>% 
  mutate(pcent = ((avg_before_2020 - avg_2020)/avg_before_2020)*100)

world_map <- map_data("world")
ggplot() +
  geom_polygon(data = world_map,
               aes(x = long, y = lat, group = group),
               fill = "lightgray", color = "white") +
  geom_point(data = pm_map, 
             aes(x = Lon, y = Lat, color = pcent),
             size = 0.1, alpha = 0.5) +
  scale_color_gradient(low = "purple", high = "orange") +
  labs(title = "Map - PM2.5",
       x = "Longitude",
       y = "Latitude")

```

```{r USA-model}

model_baseline <- city %>% 
  filter(countryCode == 'USA' | countryCode == 'CHE', parameter == 'pm25') %>% 
  filter((('2017-03-15' <= date) & (date <= '2017-05-15')) | (('2018-03-15' <= date) & (date <= '2018-05-15')) | (('2019-03-15' <= date) & (date <= '2019-05-15'))) %>%
  mutate(month = month(date, label=T), weekday = as.factor(weekdays(date, abbreviate=T))) %>% 
  mutate(is_weekday = !(weekday == 'Sun' | weekday == 'Sat'))

model <- lm(mean ~ month + is_weekday, model_baseline)

model_2020 <- city %>% 
  filter(countryCode == 'USA' | countryCode == 'CHE', parameter == 'pm25') %>% 
  filter((('2020-03-15' <= date) & (date <= '2020-05-15'))) %>%
  mutate(month = month(date, label=T), weekday = as.factor(weekdays(date, abbreviate=T))) %>% 
  mutate(is_weekday = !(weekday == 'Sun' | weekday == 'Sat')) %>% 
  add_predictions(model)

pred_model <- model_2020 %>% 
  mutate(rc = ((mean - pred)/mean)*100) %>% 
  group_by(countryCode) %>% 
  summarize(relative_change = mean(rc))



```

```{r}

```

